name: Publish Python release to PyPI

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: Build distribution packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.3.2

      - name: Build a binary wheel and a source tarball
        run: uv build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/

  pypi-publish:
    name: Publish Python release to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cpace
    permissions:
      id-token: write # mandatory for trusted publishing

    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish Python release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
